---
- name: Launch an ec2 instance
  hosts: localhost
  tasks:
    - name: create an ec2 instance
      ec2:
        key_name: ***********
        region: us-east-2
        instance_type: t2.micro
        image: ami-**********************
        wait: yes
        #group: webserver
        count: 1
        vpc_subnet_id: subnet-**********
        assign_public_ip: yes

